c_box/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from contacts.views import show_all, show_person, new_contact, modify, del_person, home

app_name = 'contacts'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('contacts/', show_all, name="contacts"),
    path('show/<int:person_id>', show_person, name='person_id'),
    path('modify/<int:person_id>', modify, name='modify'),
    path('delete/<int:person_id>', del_person, name='delete'),
    path('new/', new_contact, name='new'),
    path('new/<msg>', new_contact, name='added')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)   # dodanie ścieżki, gdzie przetrzymywane będą m.in zdjęcia

contacts/models.py
from django.db import models


TYPE_CHOICES_PRIVATE = 0
TYPE_CHOICES_BUSINESS =1

TYPE_CHOICES = (
    (TYPE_CHOICES_PRIVATE, 'prywatny'),
    (TYPE_CHOICES_BUSINESS, 'służbowy'),
)

class Address(models.Model):
    city = models.CharField(max_length=128, blank=True, null=True)
    city_code = models.CharField(max_length=6, blank=True, null=True)
    street = models.CharField(max_length=128, blank=True, null=True)
    str_no = models.CharField(max_length=6, blank=True, null=True)
    number = models.CharField(max_length=6, blank=True, null=True)

    # def __str__(self):
    #     return self.city + self.street + self.str_no + "/" + self.number


class Person(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False)
    surname = models.CharField(max_length=60, blank=False, null=False)
    comment = models.TextField(null=True)
    address = models.ForeignKey(Address, models.SET_NULL, blank=True, null=True)

    # def __str__(self):
    #     return self.surname

class Tnumber(models.Model):
    number = models.CharField(max_length=20, unique=True, null=False, blank=False)
    type = models.SmallIntegerField(choices=TYPE_CHOICES, default=0)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)

    # def __str__(self):
    #     return self.number

class Email(models.Model):
    email = models.CharField(max_length=20, unique=True, null=False, blank=False)
    type = models.SmallIntegerField(choices=TYPE_CHOICES, default=0)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)

    # def __str__(self):
    #     return self.email

class Groups(models.Model):
    g_name = models.CharField(max_length=128)
    person = models.ManyToManyField(Person)

    # def __str__(self):
    #     return self.g_name

contacts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.contrib.messages import constants as messages
from contacts.models import Person, Address, Tnumber, Email, Groups


def home(request):
    return render(request, "contacts/home.html", locals())


def show_all(request):
    people = Person.objects.order_by('surname')
    return render(request, "contacts/show_all.html", locals())


def show_person(request, person_id):
    p = get_object_or_404(Person, pk=person_id)
    tel = Tnumber.objects.filter(person=p)
    mail = Email.objects.filter(person=p)
    if request.method == "GET":
        # jeżeli istnieje adres dla tej osoby, to pobierz dane adresowe do formularza
        if p.address_id:
            a = Address.objects.get(pk=p.address_id)
            city = a.city
            city_code = a.city_code
            street = a.street
            str_no = a.str_no
            number = a.number
        return render(request, "contacts/show.html", locals())


def new_contact(request, msg=None):
    if request.method == 'GET':
        return render(request, "contacts/new_contact.html", locals())
    else:
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        new_person = Person.objects.create(name=name, surname=surname)
        new_person.save()
        msg = 'Dodano nową osobę!'
        return HttpResponseRedirect(reverse('added', kwargs={'msg': msg}))


def modify(request, person_id):
    p = get_object_or_404(Person, pk=person_id)
    tel = Tnumber.objects.filter(person=p)
    mail = Email.objects.filter(person=p)

    if request.method == "GET":
        # jeżeli istnieje adres dla tej osoby, to pobierz dane adresowe do formularza
        if p.address_id:
            a = Address.objects.get(pk=p.address_id)
            city = a.city
            city_code = a.city_code
            street = a.street
            str_no = a.str_no
            number = a.number
        return render(request, "contacts/modify.html", locals())

    else:  # na metodzie POST
        # pobierz dane, jeżeli zostały wprowadzone przez użytkownika
        city = request.POST.get('city')
        city_code = request.POST.get('city_code')
        street = request.POST.get('street')
        str_no = request.POST.get('str_no')
        number = request.POST.get('number')

        tel_number = request.POST.get('tel_number')
        tel_type = request.POST.get('tel_type')

        e_mail = request.POST.get('e_mail')
        e_type = request.POST.get('e_type')

        try:
            new_address = Address.objects.get(city=city, city_code=city_code, street=street, str_no=str_no,
                                              number=number)
        except Address.DoesNotExist:
            new_address = Address.objects.create(city=city, city_code=city_code, street=street, str_no=str_no,
                                                 number=number)
            new_address.save()
        p.address = new_address
        p.save()

        # sprawdza czy w modelu Address są puste adresy (bez Person) - tylko przy modyfikacji adresu
        try:
            empty_a = Address.objects.filter(person__isnull=True).values_list('id', flat=True)
            if not empty_a:
                pass
            else:
                empty_id = empty_a[0]
                Address.objects.get(id=empty_id).delete()
        except Address.DoesNotExist:
            pass

        # dodanie nowego nr telefonu
        if tel_number == "":  # jeżeli pole zostało puste, to idź dalej i nie zapisuj nowego tel.
            pass
        else:  # pobierz nowe dane i zapisz nowy telefon
            new_tel = Tnumber.objects.create(number=tel_number, type=tel_type, person=p)
            new_tel.save()

        # dodaie nowego maila
        if e_mail == "":
            pass
        else:
            new_email = Email.objects.create(email=e_mail, type=e_type, person=p)
            new_email.save()

        return HttpResponseRedirect(reverse('contacts'))


def del_person(request, person_id):
    p = get_object_or_404(Person, pk=person_id)
    if p.address_id:
        a_id = p.address_id
        p.delete()
        try:
            Person.objects.get(address_id=a_id)
            pass
        except Person.MultipleObjectsReturned:
            pass
        except Person.DoesNotExist:
            a = Address.objects.get(pk=a_id)
            a.delete()
    else:
        p.delete()
    return HttpResponseRedirect(reverse('contacts'))

contacts/templates/base.html
<!doctype html>
<html lang="pl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>
        {% block title %}Skrzynka kontaktowa{% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">C_Box</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'contacts' %}">Kontakty <span class="sr-only">(current)</span></a></li>
              <li class="nav-item">
                <a class="nav-link" href="../new">Dodaj</a></li>
              <li class="nav-item">
                <a class="nav-link" href="#">Edytuj</a></li>
              <li class="nav-item">
                <a class="nav-link" href="#">Usuń</a></li>
            </ul>
         </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <div class="container">
{#        {% block footer %}#}
        <div style="{% block footer_style %} text-align: right {% endblock %}">
        	Copyright by KN
        </div>
{#        {% endblock %}#}
    </div>


  </body>
</html>

contacts/templates/contacts/home.html
{% extends "base.html" %}

{% block content %}

    <div class="contener">
        <h2>Twoja lista <a href="{% url 'contacts' %}">kontaktów</a> </h2>

    </div>

{% endblock %}

{% block footer_style %}background-color: white{% endblock %}

contacts/templates/contacts/modify.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-right">{{ p.name }} {{ p.surname }}</h2>

<div style=>
          <form action="#" method="POST">
              {% csrf_token %}
                <fieldset style="background-color: whitesmoke">
                  <legend>Podaj lub zmień adres:</legend>
                     <label>Miasto: <input name="city" type="text" value={{ city }}></label>
                     <label>Kod: <input name="city_code" type="text" placeholder="00-00" value={{ city_code }}></label>
                      <br>
                    <label>Ulica: <input name="street" type="text" value="{{ street }}"></label>
                    <label>Numer domu: <input name="str_no" type="text" value="{{ str_no }}"></label>
                    <label>Numer lokalu: <input name="number" type="text" value="{{ number }}"></label>
                    <input class="btn btn-primary" type="submit" value="Zapisz">
                </fieldset>
                <p></p><br>


                <fieldset style="background-color: whitesmoke">
                  <legend>Dodaj numer telefonu:</legend>

                    <label>Numer: <input name="tel_number" type="number"></label>
                    <select name="tel_type" type="number">
                        <option value="0">Prywatny</option>
                        <option value="2">Służbowy</option>
                    </select>
                    <input class="btn btn-primary" type="submit" value="Zapisz">

                </fieldset>
                       <br>

              {% if tel %}
              <fieldset>
                  <legend>Zapisane numery: <a class="btn btn-primary" href="../" role="button">Edytuj</a></legend>

                  {% for t in tel %}
                      <label>Numer: <input name="t_number" type="number" value={{ t.number }}></label>
                      <input type="hidden" name="t_id" value={{ t.pk }}>
                      <select name="t_type" type="number">
                        <option value={{ t.type }}>{{ t.TYPE_CHOICES }}</option>     {# jak zrobić, żeby sam wybierał TYPE_CHOICES} #}
{#                        <option value="1">Domowy</option>#}
{#                        <option value="2">Służbowy</option>#}
                      </select><br>
                  {% endfor %}
                </fieldset>
              {% endif %}
                    <br>

                <fieldset style="background-color: whitesmoke">
                  <legend>Dodaj Email:</legend>
                    <label>e-mail: <input name="e_mail" type="text"></label>
                    <select name="e_type" type="number">
                        <option value="0">Prywatny</option>
                        <option value="2">Służbowy</option>
                    </select>
                    <input class="btn btn-primary" type="submit" value="Zapisz">
                </fieldset>
                    <br>

              {% if mail %}
                <fieldset>
                    <legend>Zapisane adresy email: <a class="btn btn-primary" href="../" role="button">Edytuj</a></legend>
                    {% for e in mail %}
                    <label>Email: <input name="e_mail" type="text" value={{ e.email }}></label>
                    <input type="hidden" name="e_id" value={{ e.pk }}>
                    <select name="e_type" type="number">
                    <option value={{ t.type }}>{{ t.TYPE_CHOICES }}</option>     {# jak zrobić, żeby sam wybierał TYPE_CHOICES} #}
                    {% endfor %}
                    </select>
                </fieldset>
              {% endif %}
		</form>

<p></p>

</div>
{% endblock %}
{% block footer %}
{% endblock %}

contacts/templates/contacts/new_contact.html
{% extends "base.html" %}

{% block content %}
    <h2>Dodaj osobę: </h2>
    <p></p>

<div style=>
          <form action="{% url 'new' %}" method="POST">
            {% csrf_token %}
            <label>Imię: <input name="name" type="text" required></label>
            <label>Nazwisko: <input name="surname" type="text" required></label>
            <input type="submit" value="Zapisz kontakt">
		</form>
<p></p>
    {% if msg %}
        <h2>{{ msg }}</h2>
    {% endif %}

</div>
{% endblock %}
{% block footer %}
{% endblock %}

contacts/templates/contacts/show.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-right">{{ p.name }} {{ p.surname }}
<a class="btn btn-primary" href="{% url 'modify' p.id %}" role="button">Edytuj</a></h2>

<div style=>
          <form action="#" method="POST">
              {% csrf_token %}
                <fieldset style="background-color: whitesmoke">
                  <legend>Adres:</legend>
                     <label>Miasto: <input readonly value={{ city }}></label>
                     <label>Kod: <input readonly value={{ city_code }}></label>
                      <br>
                    <label>Ulica: <input readonly value="{{ street }}"></label>
                    <label>Numer domu: <input readonly value="{{ str_no }}"></label>
                    <label>Numer lokalu: <input readonly value="{{ number }}"></label>
                </fieldset>
                <p></p>

              {% if tel %}
              <fieldset>
                  <legend>Nr telefonów:</legend>
                  {% for t in tel %}
                      <label>Numer: <input readonly value={{ t.number }}></label>
                      <select readonly>
                      <option value={{ t.type }}>{{ tnumber.get_type_display }}</option>     {# jak zrobić, żeby sam wybierał TYPE_CHOICES} #}
{#                        <option value="1">Domowy</option>#}
{#                        <option value="2">Służbowy</option>#}
                      </select><br>
                  {% endfor %}
                </fieldset>
              {% endif %}
                    <br>

              {% if mail %}
                <fieldset>
                    <legend>Zapisane adresy email:</legend>
                    {% for e in mail %}
                        <label>Email: <input readonly value={{ e.email }}></label>
                        <select readonly>
                        <option value={{ t.type }}>{{ t.TYPE_CHOICES }}</option>     {# jak zrobić, żeby sam wybierał TYPE_CHOICES} #}
                    {% endfor %}
                    </select>
                </fieldset>
              {% endif %}
		</form>

<p></p>

</div>
{% endblock %}
{% block footer %}
{% endblock %}

contacts/templates/contacts/show_all.html
{% extends "base.html" %}

{% block content %}

<h3>Lista kontaktów</h3>
    <p></p>

<div style=>

{% for p in people.all %}

    <table class="table table-striped">
		<tr>
            <td width=50%><a href="{% url 'person_id' p.id %}">{{ p.name }} {{ p.surname }}</a></td>
            <td width=25%><a class="btn btn-primary btn-sm" href="{% url 'modify' p.id %}" role="button">Edytuj</a></td>
            <td width=25%><a class="btn btn-danger btn-sm" href="{% url 'delete' p.id %}" role="button">Usuń</a></td>
		</tr>
    </table>
{% endfor %}
    <p></p>

</div>
{% endblock %}
{% block footer %}
{% endblock %}

{#btn btn-danger#}